"""add engines table

Revision ID: 803f39610312
Revises: d4637cab4493
Create Date: 2025-11-04 14:11:03.912033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '803f39610312'
down_revision: Union[str, Sequence[str], None] = 'd4637cab4493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('files_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='unique_engine_name_version')
    )
    op.create_index(op.f('ix_engines_active'), 'engines', ['active'], unique=False)
    op.create_index(op.f('ix_engines_created_date'), 'engines', ['created_date'], unique=False)
    op.create_index(op.f('ix_engines_default'), 'engines', ['default'], unique=False)
    op.create_index(op.f('ix_engines_files_updated'), 'engines', ['files_updated'], unique=False)
    op.create_index(op.f('ix_engines_last_used'), 'engines', ['last_used'], unique=False)
    op.create_index(op.f('ix_engines_name'), 'engines', ['name'], unique=False)
    op.create_index(op.f('ix_engines_version'), 'engines', ['version'], unique=False)
    op.add_column('jobs', sa.Column('engine_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_jobs_engine_id'), 'jobs', ['engine_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'engines', ['engine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_engine_id'), table_name='jobs')
    op.drop_column('jobs', 'engine_id')
    op.drop_index(op.f('ix_engines_version'), table_name='engines')
    op.drop_index(op.f('ix_engines_name'), table_name='engines')
    op.drop_index(op.f('ix_engines_last_used'), table_name='engines')
    op.drop_index(op.f('ix_engines_files_updated'), table_name='engines')
    op.drop_index(op.f('ix_engines_default'), table_name='engines')
    op.drop_index(op.f('ix_engines_created_date'), table_name='engines')
    op.drop_index(op.f('ix_engines_active'), table_name='engines')
    op.drop_table('engines')
    # ### end Alembic commands ###
